footballnews/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_view,name='home'),
    path('home/',views.home_view2,name='home2'),
    path('profile/',views.ProfileTemplateView.as_view(),name='profile'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/',views.Test.as_view(),name='test'),
    path('thanks/',views.Thanks.as_view(),name='thanks'),
    path('posts/',include('posts.urls', namespace = 'posts')),
    path('groups/',include('groups.urls', namespace = 'groups')),
    path('articles/', include('articles.urls',namespace='articles')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/urls.py
from django.urls import path, re_path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    re_path(r'^posts/in/(?P<slug>[-\w]+)/$', views.SingleGroup.as_view(), name='single'),
    re_path(r'^join/(?P<slug>[-\w]+)/$', views.JoinGroup.as_view(), name='join'),
    re_path(r'^leave/(?P<slug>[-\w]+)/$', views.LeaveGroup.as_view(), name='leave'),
    
]

posts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path('articles/comment/<int:article_id>/',views.CreatePostSpecific.as_view(), name='specific'),

    path("by/<str:username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<str:username>/<int:pk>/", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name="delete"),
]

groups/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.text import slugify

import markdown

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = markdown.markdown(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["name"]

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from groups.models import Group,GroupMember
from . import models

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}


<h1 class="gdtitle">{{group.name}}</h1>
<p class="gddesc"><strong>   {{ group.description }}</strong></p>
<div class="col-md-4">
	<span class="badge">{{ group.members.count }}</span> Follower{{ group.members.count|pluralize }}
</div>

<br>
<hr>
  <div class="content">


				{% if user in group.members.all %}
					<a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Unfollow</a>
				{% else %}
					<a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Follow</a>
				{% endif %}



</div>

{% endblock %}


{% block group_content %}


<div class="container-fluid">
<div>
	<h3>ARTICLES: </h3>
	{% if group.articles.count == 0 %}

	<h2>NO ARTCILES YET  </h2>
	{% else %}
	{% for article in group.articles.all %}
	{% include "articles/_article.html" %}
	{% endfor %}
	{% endif %}
</div>

</div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap3 %}


{% block group_content %}
<h4>CREATE A NEW GROUP HERE..</h4>

<form action="{% url 'groups:create' %}"   method="post"  id="groupForm">


    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="CREATE YOUR GROUP!">
</form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		
	<br>
	<br>
	<br>
	<br>
			<h2>POPULAR TOPICS:  </h2>

	</div>
	
</div>
{% endblock %}

{% block group_content %}
<div class="card">
<div class="col-md-8">
	<div class="list-group">
		<i><h5>FOLLOWING</h5></i>

		{% for group in object_list %}
		{% if user in group.members.all %}
		<a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			<h3 class="title list-group-item-heading">{{ group.name }}</h3>
	   <div class="list-group-item-text container-fluid">
		   {{ group.description_html|safe }}
		   <div class="row">
			   
			   <div class="col-md-4">
				   <span class="badge">{{ group.members.count }}</span> follower{{ group.members.count|pluralize }}
			   </div>
			   <div class="col-md-4">
				   <span class="badge">{{ group.articles.count }}</span> Article{{ group.articles.count|pluralize }}
			   </div>
		   </div>
	   </div>
   </a>
		{% endif %}
		{% endfor %}
		<br>
		<br>
		<hr>
		<i><h5>OTHERS</h5></i>

		{% for group in object_list %}
		{% if user not in group.members.all %}
		  <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> follower{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.articles.count }}</span> Article{{ group.articles.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endif %}
		{% endfor %}
		
	</div>
</div>
</div>
{% endblock %}