accounts/urls.py
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path


app_name = 'accounts'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'),
         name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup')
]

articles/urls.py
from django.urls import path,re_path
from . import views


app_name = 'articles'


urlpatterns = [
    path('',views.ArticleList.as_view(),name='all'),
    path('bookmarks/',views.Bookmarked.as_view(),name='bookmarks'),
    path('new/',views.CreateArticle.as_view(),name='create'),
    path('delete/<int:pk>/',views.DeleteArticle.as_view(),name='delete'),
    path('by/<str:username>/<int:pk>/',views.ArticleDetail.as_view(),name='single'),
    path('by/<str:username>/',views.UserArticles.as_view(),name="for_user"),
    path('list/',views.ArticleListView.as_view(),name='list'),
    path('article/<int:pk>/like/', views.LikeCreate.as_view(), name='like_article'),
    path('article/<int:pk>/bookmark/', views.BookMarkCreate.as_view(), name='bookmark_article'),

    re_path(r'^posts/in/(?P<message_html>[-\w]+)/$', views.SingleArticle.as_view(), name='single_article'),





]

footballnews/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_view,name='home'),
    path('home/',views.home_view2,name='home2'),
    path('profile/',views.ProfileTemplateView.as_view(),name='profile'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/',views.Test.as_view(),name='test'),
    path('thanks/',views.Thanks.as_view(),name='thanks'),
    path('posts/',include('posts.urls', namespace = 'posts')),
    path('groups/',include('groups.urls', namespace = 'groups')),
    path('articles/', include('articles.urls',namespace='articles')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path('articles/comment/<int:article_id>/',views.CreatePostSpecific.as_view(), name='specific'),

    path("by/<str:username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<str:username>/<int:pk>/", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name="delete"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>F-FOOTBALL NEWS</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">



  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">PHILIP BLOG</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                   <h4>MENU</h4> 
                  </a>
                  <ul class="dropdown-menu">
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'groups:all' %}">View Topics</a></li>
                    <li><a class="dropdown-item" href="{% url 'profile' %}">View Profile</a></li>
                    <li><hr class="dropdown-divider"></li>

                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">LOGOUT</a></li>
                  </ul>
                </li>
    						
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>
        



<canvas id="canvas"></canvas>


<link rel="stylesheet" href="{% static 'footballnews/css/master.css'%}">

  </body>
  <!-- <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script> -->
</html>

templates/home.html
{% extends "articles/article_base.html" %}

{% block article_content %}
{% if user.is_authenticated %}
<h1 class="grand">FOLLOWING</h1>
{% for article in articles %}
<div class="card mb-4 custom-card" style="border: 2px solid #ccc; width: 60%; margin: 0 auto;">
    <div class="card-body">
        <h3 class="card-title">
            <strong><a href="{% url 'articles:single' username=article.user.username pk=article.pk %}">{{ article.title|safe }}</a></strong>
        </h3>

        <div class="image-container text-center my-5 image" style="border: 2px solid rgb(2, 2, 2);  margin: 0 auto;">
            <a href="{% url 'articles:single' username=article.user.username pk=article.pk %}"><img src="{{ article.image.url }}" alt="{{ article.title }}" class="img-fluid image" style="width: 650px; "></a>
        </div>
        
        <h5 class="card-text">{{ article.message_html|safe }}</h5>
        
        <div class="media-body">
            <h5 class="media-heading">
                <span class="username">
                    <a href="{% url 'articles:for_user' username=article.user.username %}">by -- @{{ article.user.username }}</a>
                </span>
                <time class="time">{{ article.created_date }}</time>

            </h5>
            <div class="media-footer">

                
                <span class="badge">{{ article.total_likes }}</span> like{{ article.total_likes|pluralize }}
                <span class="badge">{{ article.total_bookmarks }}</span> bookmark{{ article.total_likes|pluralize }}



                
                <br>


                {% if user.is_authenticated and article.user == user and not hide_delete %}
                    <a href="{% url 'articles:delete' pk=article.pk %}" title="delete" class="btn btn-danger">
                        <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                        <span class="text-danger icon-label">Delete</span>
                    </a>
                {% endif %}
                <form method="post" action="{% url 'articles:like_article' article.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">
                        <span class="glyphicon glyphicon-heart"></span> 
                    </button>
                </form>
                
                <form method="post" action="{% url 'articles:bookmark_article' article.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-info">
                        <span class="glyphicon glyphicon-bookmark"></span> 
                    </button>
                </form>
                
                
            </div>
        </div>
    </div>

    <div class="card-footer">
        {% if article.posts.count == 0 %}
            <h5>No comments available yet..</h5>
            <h6><a href="{% url 'posts:specific' article_id=article.pk %}">Add comment+</a></h6>

        {% else %}
        <h6><a href="{% url 'posts:specific' article_id=article.pk %}">Add comment+</a></h6>

            <h6><a href="{% url 'articles:single' username=article.user.username pk=article.pk %}">View Comments?</a></h6>

        {% endif %}
        {% if article.group %}
        <div class="groupn">
        <span class="group-name">
             <a href="{% url 'groups:single' slug=article.group.slug %}">{{ article.group.name }}</a>
        </span>
    </div>
    {% endif %}
    </div>
</div>

<br>
<br>
<br>
<br>
<br>
{% endfor %}


{% else %}
<h2>LOGIN TO CONTINUE...</h2>
<h3><a href="{% url 'accounts:login' %}">LOGIN</a></h3>
{% endif %}
{% endblock %}

templates/home2.html
{% extends "articles/article_base.html" %}

{% block article_content %}
{% if user.is_authenticated %}
<h5>Seems you are not following any topic yet...</h5>
<h6><a href="{% url 'home2' %}">View Trending Articles?</a></h6>
<h6><a href="{% url 'groups:all' %}">Start Following some Topics</a></h6>


{% for article in articles %}
<div class="card mb-4 custom-card" style="border: 2px solid #ccc; width: 60%; margin: 0 auto;">
    <div class="card-body">
        <h3 class="card-title">
            <strong><a href="{% url 'articles:single' username=article.user.username pk=article.pk %}">{{ article.title|safe }}</a></strong>
        </h3>

        <div class="image-container text-center my-5 image" style="border: 2px solid rgb(2, 2, 2);  margin: 0 auto;">
            <a href="{% url 'articles:single' username=article.user.username pk=article.pk %}"><img src="{{ article.image.url }}" alt="{{ article.title }}" class="img-fluid image" style="width: 650px; "></a>
        </div>
        
        <h5 class="card-text">{{ article.message_html|safe }}</h5>
        
        <div class="media-body">
            <h5 class="media-heading">
                <span class="username">
                    <a href="{% url 'articles:for_user' username=article.user.username %}">by -- @{{ article.user.username }}</a>
                </span>
                <time class="time">{{ article.created_date }}</time>

            </h5>
            <div class="media-footer">

                
                <span class="badge">{{ article.total_likes }}</span> like{{ article.total_likes|pluralize }}
                <span class="badge">{{ article.total_bookmarks }}</span> bookmark{{ article.total_likes|pluralize }}



                
                <br>


                {% if user.is_authenticated and article.user == user and not hide_delete %}
                    <a href="{% url 'articles:delete' pk=article.pk %}" title="delete" class="btn btn-danger">
                        <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                        <span class="text-danger icon-label">Delete</span>
                    </a>
                {% endif %}
                <form method="post" action="{% url 'articles:like_article' article.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">
                        <span class="glyphicon glyphicon-heart"></span> 
                    </button>
                </form>
                
                <form method="post" action="{% url 'articles:bookmark_article' article.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-info">
                        <span class="glyphicon glyphicon-bookmark"></span> 
                    </button>
                </form>
                
                
            </div>
        </div>
    </div>

    <div class="card-footer">
        {% if article.posts.count == 0 %}
            <h5>No comments available yet..</h5>
            <h6><a href="{% url 'posts:specific' article_id=article.pk %}">Add comment+</a></h6>

        {% else %}
        <h6><a href="{% url 'posts:specific' article_id=article.pk %}">Add comment+</a></h6>

            <h6><a href="{% url 'articles:single' username=article.user.username pk=article.pk %}">View Comments?</a></h6>

        {% endif %}
        {% if article.group %}
        <div class="groupn">
        <span class="group-name">
             <a href="{% url 'groups:single' slug=article.group.slug %}">{{ article.group.name }}</a>
        </span>
    </div>
    {% endif %}
    </div>
</div>

<br>
<br>
<br>
<br>
<br>
{% endfor %}







{% else %}
<h2>LOGIN TO CONTINUE...</h2>
<h3><a href="{% url 'accounts:login' %}">LOGIN</a></h3>
{% endif %}
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{%  block content %}
<div class="container-fluid">
    <h5><strong><a href="{% url 'profile' %}">@ {{ user.username }}</a></strong></h5>

    <li><a class="dropdown-item" href="{% url 'articles:create' %}">Create An Article</a></li>
    <hr>
    <strong><h5><a href="{% url 'posts:for_user' username=user.username %}">YOUR COMMENTS</a></h5></strong>
    <strong><h5><a href="{% url 'articles:for_user' username=user.username %}">YOUR ARTICLES</a></h5></strong>
    <strong><a class="dropdown-item" href="{% url 'articles:bookmarks' %}">Bookmarks</a></strong>


</div>
{% endblock %}

templates/search_form.html
<!-- search_form.html -->
{% extends 'base.html' %}
{% block content %}
<form method="get" action="{% url 'search' %}">
    {{ form.query.label_tag }}
    {{ form.query }}
    <button type="submit">Search</button>
</form>
{% endblock %}

templates/search_results.html
<!-- search_results.html -->
{% extends 'base.html' %}
{% block content %}
{% if results %}
    <h2>Search Results:</h2>
    <ul>
        {% for article in results %}
            <li><a href="{% url 'article_detail' article.id %}">{{ article.title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No results found.</p>
{% endif}
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="container">
  <h1>HI!   <a href="{% url 'profile' %}">@{{ user.username }}</a></h1>
  <h5><a href="{% url 'home'%}">VIEW FOLLOWING ARTICLES..</a></h5>


</div>



<link rel="stylesheet" href="{% static 'footballnews/css/master2.css'%}">
<link rel="stylesheet" href="{% static 'footballnews/js/master3.css'%}">
{% endblock %}

templates/thanks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<h3>Waiting for your return ⌛</h3>
{% load static %}
<div id="watch">
    <div class="frame-face"></div>
    <ul class="minute-marks">
      <li></li><li></li><li></li><li></li><li></li><li></li>
      <li></li><li></li><li></li><li></li><li></li><li></li>
      <li></li><li></li><li></li><li></li><li></li><li></li>
      <li></li><li></li><li></li><li></li><li></li><li></li>
      <li></li><li></li><li></li><li></li><li></li><li></li>
      <li></li><li></li><li></li><li></li><li></li><li></li>
      <li></li><li></li><li></li><li></li><li></li><li></li>
      <li></li><li></li><li></li><li></li><li></li><li></li>
    </ul>
    <div class="digital-wrap">
      <ul class="digit-hours">
        <li>23</li>
        <li>00</li><li>01</li><li>02</li><li>03</li><li>04</li><li>05</li>
        <li>06</li><li>07</li><li>08</li><li>09</li><li>10</li><li>11</li>
        <li>12</li><li>13</li><li>14</li><li>15</li><li>16</li><li>17</li>
        <li>18</li><li>19</li><li>20</li><li>21</li><li>22</li>
      </ul>
      <ul class="digit-minutes">
        <li>10</li><li>11</li>
        <li>12</li><li>13</li><li>14</li><li>15</li><li>16</li><li>17</li>
        <li>18</li><li>19</li><li>20</li><li>21</li><li>22</li><li>23</li>
        <li>24</li><li>25</li><li>26</li><li>27</li><li>28</li><li>29</li>
        <li>30</li><li>31</li><li>32</li><li>33</li><li>34</li><li>35</li>
        <li>36</li><li>37</li><li>38</li><li>39</li><li>40</li><li>41</li>
        <li>42</li><li>43</li><li>44</li><li>45</li><li>46</li><li>47</li>
        <li>48</li><li>49</li><li>50</li><li>51</li><li>52</li><li>53</li>
        <li>54</li><li>55</li><li>56</li><li>57</li><li>58</li><li>59</li>
        <li>00</li><li>01</li><li>02</li><li>03</li><li>04</li><li>05</li>
        <li>06</li><li>07</li><li>08</li><li>09</li>
      </ul>
      <ul class="digit-seconds">
        <li>20</li><li>21</li><li>22</li><li>23</li>
        <li>24</li><li>25</li><li>26</li><li>27</li><li>28</li><li>29</li>
        <li>30</li><li>31</li><li>32</li><li>33</li><li>34</li><li>35</li>
        <li>36</li><li>37</li><li>38</li><li>39</li><li>40</li><li>41</li>
        <li>42</li><li>43</li><li>44</li><li>45</li><li>46</li><li>47</li>
        <li>48</li><li>49</li><li>50</li><li>51</li><li>52</li><li>53</li>
        <li>54</li><li>55</li><li>56</li><li>57</li><li>58</li><li>59</li>
        <li>00</li><li>01</li><li>02</li><li>03</li><li>04</li><li>05</li>
        <li>06</li><li>07</li><li>08</li><li>09</li><li>10</li><li>11</li>
        <li>12</li><li>13</li><li>14</li><li>15</li><li>16</li><li>17</li>
        <li>18</li><li>19</li>
      </ul>
    </div>
    <ul class="digits">
      <li>1</li><li>2</li><li>3</li><li>4</li><li>5</li><li>6</li>
      <li>7</li><li>8</li><li>9</li><li>10</li><li>11</li><li>12</li>
    </ul>
    <div class="hours-hand"></div>
    <div class="minutes-hand"></div>
    <div class="seconds-hand"></div>
  </div>
  <link rel="stylesheet" href="{% static 'footballnews/css/master2.css'%}">
{% endblock %}