footballnews/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_view,name='home'),
    path('home/',views.home_view2,name='home2'),
    path('profile/',views.ProfileTemplateView.as_view(),name='profile'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/',views.Test.as_view(),name='test'),
    path('thanks/',views.Thanks.as_view(),name='thanks'),
    path('posts/',include('posts.urls', namespace = 'posts')),
    path('groups/',include('groups.urls', namespace = 'groups')),
    path('articles/', include('articles.urls',namespace='articles')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path('articles/comment/<int:article_id>/',views.CreatePostSpecific.as_view(), name='specific'),

    path("by/<str:username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<str:username>/<int:pk>/", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name="delete"),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

import markdown
from django.contrib.auth import get_user_model
from articles.models import Article



User  = get_user_model()
# Create your models here.
 
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    article = models.ForeignKey(Article,related_name='posts',on_delete=models.CASCADE,null=True,blank=True)


    def __str__(self):
        return self.message
    

    def save(self, *args, **kwargs):
        self.message_html = markdown.markdown(self.message)
        super().save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('posts:single', 
                       kwargs={'username': self.user.username,
                               
                                               'pk':self.pk})
    
    class Meta:
        ordering = ['-created_at']
        unique_together = ('user','message')

posts/forms.py
from django import forms
from .models import Post
from articles.models import Article
from django.shortcuts import get_object_or_404



class CreatePostSpecificForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', 'article']

    def __init__(self, *args, **kwargs):
        article_id = kwargs.pop('article_id', None)
        super().__init__(*args, **kwargs)

        if article_id is not None:
            article = get_object_or_404(Article, pk=article_id)
            # Set the 'article' field as hidden and set the initial value
            self.fields['article'].widget = forms.HiddenInput()
            self.fields['article'].initial = article

posts/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models,forms
from articles.models import Article
from django.contrib import messages
from .forms import CreatePostSpecificForm
from django.shortcuts import get_object_or_404
from django.views import generic
from django.http import Http404,HttpResponse
from django.urls import reverse_lazy
from braces.views import SelectRelatedMixin
from django.contrib.auth import get_user_model


# Create your views here.
User = get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
     model = models.Post
     select_related = ('user','article')



class UserPosts(generic.ListView):
     model = models.Post
     template_name = 'posts/user_post_list'

 
     def get_queryset(self):
                try:
                    self.post_user = User.objects.prefetch_related("posts").get(
                        username__iexact=self.kwargs.get("username")
                        # to get posts related to the user
                    )
                except User.DoesNotExist:
                      raise Http404
                else:
                      return self.post_user.posts.all()
                
     def get_context_data(self, **kwargs):
           context = super().get_context_data(**kwargs)
           context['post_user'] = self.post_user
           return context
                
class PostDetail(SelectRelatedMixin, generic.DetailView):
      model = models.Post
      select_related = ("user","article")

      def get_queryset(self):
            queryset = super().get_queryset()
            return queryset.filter(
                              user__username__iexact=self.kwargs.get("username")

            )
      
class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    
    fields = ('message','article')
    model = models.Post

    

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)
    
class CreatePostSpecific(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    model = models.Post
    form_class = CreatePostSpecificForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['article_id'] = self.kwargs.get('article_id')  # Pass article_id from URL parameters to the form
        return kwargs





class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
      model = models.Post
      select_related = ("user","article")
      success_url = reverse_lazy("profile")        
                

      def get_queryset(self):
        queryset = super().get_queryset()
        if queryset.exists():
            return queryset.filter(user_id=self.request.user.id)
        else:
             HttpResponse('You already deleted this comment silly:)')

      def delete(self, *args, **kwargs):
          messages.success(self.request, "Post Deleted")
          return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<div class="post media">
	<h6><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.message_html|safe }}</a></h6>
	<div class="media-body">
		<!-- <strong>{{ post.user.username }}</strong> -->
		<h5 class="media-heading">
			<span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">by -- @{{ post.user.username }}</a></span>
			<time class="time">{{ post.created_at }}</time>
			{% if post.group %}
            <span class="group-name">in <a href="#">{{ post.article.name }}</a></span>
			{% endif %}
		</h5>




		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        {% block prepost %}{% endblock %}
        {% block post_content %}{% endblock %}
        {% block post_post %}{% endblock %}
    </div>
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}


{% block post_content %}
<div class="centerform">
<h3>Are you sure you want to delete this comment?  </h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST" class="articleform">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>
</div>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="col-md-8">
    {% include "posts/_post.html" %}
</div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap3 %}

{% block content %}
<form   id="postform" action="{% url 'posts:create' %}" method="post" class="articleform">


    {% csrf_token %}
    {% bootstrap_form form %}

<input type="submit" value="Post Comment" id="" class="btn btn-primary">

</form>
<a href="{% url 'posts:for_user' username=user.username %}">VIEW YOUR COMMENTS</a>


{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}


{% block pre_post_content %}

<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{# {% get_user_groups as user_groups %}#}
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %}#}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>
			



		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
<div class="col-md-4">
    <h1>{{ post_user.username }}</h1>
</div>
{% endblock %}


{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
    {% include "posts/_post.html" %}
    {% endfor %}
</div>